import { session } from "@/utils/utils";
export default [
    {
        path: "yonghu/add",
        name: "IndexyonghuAdd",
        component: () => import("@/views/yonghu/add-web.vue"),
        meta: { title: "用户添加" },
    },
    {
        path: "yonghu/detail",
        name: "IndexyonghuDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/yonghu/detail-web.vue"),
        meta: { title: "用户详情" },
    },
    {
        path: "shoucang/add",
        name: "IndexshoucangAdd",
        component: () => import("@/views/shoucang/add-web.vue"),
        meta: { title: "收藏添加", authLogin: true, msg: true },
    },
    {
        path: "dianzan/add",
        name: "IndexdianzanAdd",
        component: () => import("@/views/dianzan/add-web.vue"),
        meta: { title: "点赞添加", authLogin: true, msg: true },
    },
    {
        path: "biji",
        name: "IndexbijiList",
        component: () => import("@/views/biji/index.vue"),
        meta: { title: "笔记列表" },
    },
    {
        path: "biji/detail",
        name: "IndexbijiDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/biji/detail-web.vue"),
        meta: { title: "笔记详情" },
    },
    {
        path: "youxi/category",
        name: "IndexyouxiCategory",
        component: () => import("@/views/youxi/category.vue"),
        meta: { title: "游戏分类" },
    },
    {
        path: "youxi/detail",
        name: "IndexyouxiDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/youxi/detail-web.vue"),
        meta: { title: "游戏详情" },
    },
    {
        path: "zhongcao/add",
        name: "IndexzhongcaoAdd",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/zhongcao/add-web.vue"),
        meta: { title: "种草添加" },
    },
    {
        path: "pinglun/add",
        name: "IndexpinglunAdd",
        component: () => import("@/views/pinglun/add-web.vue"),
        meta: { title: "评论添加", authLogin: true, msg: true },
    },
    {
        path: "pinglunhuifu/add",
        name: "IndexpinglunhuifuAdd",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/pinglunhuifu/add-web.vue"),
        meta: { title: "评论回复添加", authLogin: true, msg: true },
    },
    {
        path: "guanzhu/add",
        name: "IndexguanzhuAdd",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/guanzhu/add-web.vue"),
        meta: { title: "关注添加", authLogin: true, msg: true },
    },
    {
        path: "siliao/detail",
        name: "IndexsiliaoDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/siliao/detail-web.vue"),
        meta: { title: "私聊详情", authLogin: true, msg: true },
    },
    {
        path: "topic",
        name: "IndexTopicList",
        component: () => import("@/views/topic/index.vue"),
        meta: { title: "话题广场" },
    },
    {
        path: "history",
        name: "IndexHistory",
        component: () => import("@/views/history/index.vue"),
        meta: { title: "浏览历史" },
    },
    {
        path: "my/activity",
        name: "IndexMyActivity",
        component: () => import("@/views/my/activity.vue"),
        meta: { title: "我的收藏点赞", authLogin: true, msg: true },
    },
    {
        path: "my/dashboard",
        name: "IndexMyDashboard",
        component: () => import("@/views/my/dashboard.vue"),
        meta: { title: "数据看板", authLogin: true, msg: true },
    },
    {
        path: "my/growth",
        name: "IndexMyGrowth",
        component: () => import("@/views/my/growth.vue"),
        meta: { title: "成长中心", authLogin: true, msg: true },
    },
    {
        path: "my/profile",
        name: "IndexMyProfile",
        component: () => import("@/views/my/profile.vue"),
        meta: { title: "我的主页", authLogin: true, msg: true },
    },
    {
        path: "topic/detail",
        name: "IndexTopicDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/topic/detail.vue"),
        meta: { title: "话题详情" },
    },
    {
        path: "mall/products",
        name: "IndexMallList",
        component: () => import("@/views/mall/list.vue"),
        meta: { title: "周边商城" },
    },
    {
        path: "mall/detail",
        name: "IndexMallDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/mall/detail.vue"),
        meta: { title: "商品详情" },
    },
    {
        path: "mall/cart",
        name: "IndexMallCart",
        component: () => import("@/views/mall/cart.vue"),
        meta: { title: "购物车", authLogin: true },
    },
    {
        path: "mall/order/list",
        name: "IndexMallOrderList",
        component: () => import("@/views/mall/order-list.vue"),
        meta: { title: "我的订单", authLogin: true },
    },
    {
        path: "mall/order/detail",
        name: "IndexMallOrderDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/mall/order-detail.vue"),
        meta: { title: "订单详情", authLogin: true },
    },
    {
        path: "ai",
        name: "IndexAiRecommend",
        component: () => import("@/views/ai/index.vue"),
        meta: { title: "AI 推荐" },
    },
];
